spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-156-110-139.compute-1.amazonaws.com:5432/d5334omja5plsr
    username: ojpaffjyaudfvu
    password: bcc2b93e94337b070dcc6f12ad06eb75dd5f72823bded1e1fb64b6424b0066a6
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
logging:
  level:
    org:
      springframework:
        web: TRACE
email:
  username: ngocsangair01@gmail.com
  password: gawjkvhsdvktuhzv